apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: rec-large-scale-5nodes
spec:
  # The number of Redis Enterprise nodes in the clusters.
  nodes: 5

  persistentSpec:
    # Whether to enable persistent storage for the Redis Enterprise nodes.
    enabled: true

    # The size of the persistent volume for each Redis Enterprise node.
    volumeSize: 500Gi
    
  redisEnterpriseNodeResources:
    limits:
      cpu: 62000m
      memory: 400Gi
    requests:
      cpu: 6200m
      memory: 400Gi
