apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-tcp-proxy-config
  namespace: rec-large-scale
data:
  haproxy.cfg: |
    global
      daemon
      maxconn 256

    defaults
      mode tcp
      timeout connect 5s
      timeout client 50s
      timeout server 50s

    frontend redis_frontend
      bind *:12000
      default_backend redis_backend

    backend redis_backend
      mode tcp
      server redis primary.rec-large-scale.svc.cluster.local:11793 check ssl verify none
