apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primary-haproxy-ingress
  namespace: rec-large-scale
  annotations:
    kubernetes.io/ingress.class: haproxy
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
    - host: primary-db.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: primary
                port:
                  number: 12462
