apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: replicaof # name this whatever you wish
spec:
  replicaSources:
   - replicaSourceType: SECRET
     replicaSourceName: primary-url # Use our custom secret for the primary database
  memorySize: 200GiB
  evictionPolicy: volatile-lru
  databasePort: 13000
  modulesList:
  - name: search
    config: "MT_MODE MT_MODE_FULL WORKER_THREADS 12"
  - name: bf
  - name: ReJSON
  - name: timeseries
  redisEnterpriseCluster:
    name: rec-large-scale-5nodes # Change this to whatever you named the REC
  replication: false
  ossCluster: false            # Explicitly disable OSS Cluster API
  shardCount: 40
  persistence: disabled
  tlsMode: enabled             # MUST be enabled for HAProxy
  shardsPlacement: "sparse"
