apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-enterprise-storage-rec-large-scale-5nodes-0
  namespace: rec-large-scale
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
