#cloud-config

package_update: true
package_upgrade: true
packages:
  - git
  - dpkg-dev
  - gcc
  - g++
  - libc6-dev
  - libssl-dev
  - make
  - cmake
  - clang
  - automake
  - autoconf
  - libtool
  - ca-certificates
  - wget
  - zip

# Create the Redis installation script
write_files:
  - path: /tmp/install_redis.sh
    permissions: "0755"
    content: |
      #!/bin/bash

      set -e # exit immediately on error

      GH_ORG=${1:-"redis"}
      GH_REPO=${2:-"redis"}
      COMMIT=${3:-"HEAD"}
      FOLDER=${4:-${GH_REPO}}

      echo "Installing ${GH_ORG}/${GH_REPO} at commit ${COMMIT} in folder ${FOLDER}"
      rm -rf ${FOLDER}
      git clone https://github.com/${GH_ORG}/${GH_REPO} ${FOLDER}

      cd ${FOLDER}
      git checkout ${COMMIT}

      make distclean
      make BUILD_TLS=yes -j
      sudo make install

      echo "Installed successfully"


# Run the installation script
runcmd:
  - [su, ubuntu, -c, "/tmp/install_redis.sh redis redis unstable ~/redis-unstable"]
  - [echo, "Cloud-init installation completed"]
